apiVersion: v2
name: prometheus-conntrack-stats-exporter
description: A Helm chart for conntrack-stats-exporter
type: application
version: 0.5.12
appVersion: v0.4.20
home: https://github.com/jwkohnen/conntrack-stats-exporter
sources:
  - https://github.com/jwkohnen/conntrack-stats-exporter
  - https://github.com/nholuongut/helm-charts/tree/main/charts/prometheus-conntrack-stats-exporter
keywords:
  - conntrack
  - monitoring
  - prometheus
maintainers:
  - name: monotek
    email: monotek23@gmail.com
