apiVersion: v2
type: application
version: 15.0.0
name: prometheus-operator-crds
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: |
  A Helm chart that collects custom resource definitions (CRDs) from the Prometheus Operator, allowing for seamless
  integration with GitOps tools
keywords:
  - prometheus
  - crds
appVersion: v0.77.1
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/nholuongut/helm-charts
maintainers:
  - name: dacamposol
    email: dacamposol@gmail.com
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: QuentinBisson
    email: quentin.bisson@gmail.com
  - name: nholuongut
    email: luongutnho@hotmail.com
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/nholuongut/helm-charts
  artifacthub.io/maintainers: |
    - name: dacamposol
      email: dacamposol@gmail.com
    - name: desaintmartin
      email: cedric@desaintmartin.fr
    - name: QuentinBisson
      email: quentin.bisson@gmail.com

dependencies:
  - name: crds
    version: "0.0.0"
